[2023-05-27 22:57:56,004] INFO in _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[2023-05-27 22:57:56,005] INFO in _internal: [33mPress CTRL+C to quit[0m
[2023-05-27 22:58:02,897] ERROR in app: Exception on /f [GET]
Traceback (most recent call last):
  File "D:\CODES\flask_security\venv\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CODES\flask_security\venv\Lib\site-packages\flask\app.py", line 1458, in dispatch_request
    self.raise_routing_exception(req)
  File "D:\CODES\flask_security\venv\Lib\site-packages\flask\app.py", line 1440, in raise_routing_exception
    raise request.routing_exception  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CODES\flask_security\venv\Lib\site-packages\flask\ctx.py", line 353, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CODES\flask_security\venv\Lib\site-packages\werkzeug\routing\map.py", line 652, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\CODES\flask_security\venv\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CODES\flask_security\venv\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CODES\flask_security\venv\Lib\site-packages\flask\app.py", line 1341, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CODES\flask_security\venv\Lib\site-packages\flask\app.py", line 1281, in handle_http_exception
    return self.ensure_sync(handler)(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CODES\flask_security\app\__init__.py", line 66, in not_found_error
    return render_template('404.html'), 404
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CODES\flask_security\venv\Lib\site-packages\flask\templating.py", line 151, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CODES\flask_security\venv\Lib\site-packages\flask\templating.py", line 132, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CODES\flask_security\venv\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "D:\CODES\flask_security\venv\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\CODES\flask_security\app\templates\404.html", line 33, in top-level template code
    <img src="{{ url_for('main.static', filename='images/404.jpg') }}" alt="Page Not found Image">
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CODES\flask_security\venv\Lib\site-packages\flask\app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CODES\flask_security\venv\Lib\site-packages\flask\app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CODES\flask_security\venv\Lib\site-packages\werkzeug\routing\map.py", line 947, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'main.static' with values ['filename']. Did you mean 'static' instead?
[2023-05-27 22:58:02,906] INFO in _internal: 127.0.0.1 - - [27/May/2023 22:58:02] "[35m[1mGET /f HTTP/1.1[0m" 500 -
[2023-05-27 22:59:28,934] INFO in _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[2023-05-27 22:59:28,935] INFO in _internal: [33mPress CTRL+C to quit[0m
[2023-05-27 22:59:31,010] INFO in _internal: 127.0.0.1 - - [27/May/2023 22:59:31] "[33mGET /f HTTP/1.1[0m" 404 -
[2023-05-27 22:59:31,396] INFO in _internal: 127.0.0.1 - - [27/May/2023 22:59:31] "GET /static/images/404.jpg HTTP/1.1" 200 -
[2023-05-27 22:59:40,634] INFO in _internal: 127.0.0.1 - - [27/May/2023 22:59:40] "GET /main/ HTTP/1.1" 200 -
[2023-05-27 22:59:41,018] INFO in _internal: 127.0.0.1 - - [27/May/2023 22:59:41] "[33mGET /static/css/bootstrap.min.css HTTP/1.1[0m" 404 -
[2023-05-27 22:59:46,164] INFO in _internal: 127.0.0.1 - - [27/May/2023 22:59:46] "GET /main/register HTTP/1.1" 200 -
[2023-05-27 23:00:10,754] INFO in _internal: 127.0.0.1 - - [27/May/2023 23:00:10] "POST /main/register HTTP/1.1" 200 -
[2023-05-27 23:00:28,625] INFO in _internal: 127.0.0.1 - - [27/May/2023 23:00:28] "POST /main/register HTTP/1.1" 200 -
[2023-05-27 23:00:36,620] INFO in _internal: 127.0.0.1 - - [27/May/2023 23:00:36] "GET /main/login HTTP/1.1" 200 -
[2023-05-27 23:00:43,381] ERROR in app: Exception on /main/login [POST]
Traceback (most recent call last):
  File "D:\CODES\flask_security\venv\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CODES\flask_security\venv\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CODES\flask_security\venv\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CODES\flask_security\venv\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CODES\flask_security\venv\Lib\site-packages\flask_limiter\extension.py", line 1191, in __inner
    R, flask.current_app.ensure_sync(cast(Callable[P, R], obj))(*a, **k)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CODES\flask_security\app\routes.py", line 160, in login
    user = User.query.filter_by(email=form.email.data).first()
                                      ^^^^^^^^^^
AttributeError: 'LoginForm' object has no attribute 'email'
[2023-05-27 23:00:43,385] INFO in _internal: 127.0.0.1 - - [27/May/2023 23:00:43] "[35m[1mPOST /main/login HTTP/1.1[0m" 500 -
[2023-05-27 23:01:15,456] ERROR in app: Exception on /main/login [POST]
Traceback (most recent call last):
  File "D:\CODES\flask_security\venv\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CODES\flask_security\venv\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CODES\flask_security\venv\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CODES\flask_security\venv\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CODES\flask_security\venv\Lib\site-packages\flask_limiter\extension.py", line 1191, in __inner
    R, flask.current_app.ensure_sync(cast(Callable[P, R], obj))(*a, **k)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CODES\flask_security\app\routes.py", line 160, in login
    user = User.query.filter_by(email=form.email.data).first()
                                      ^^^^^^^^^^
AttributeError: 'LoginForm' object has no attribute 'email'
[2023-05-27 23:01:15,458] INFO in _internal: 127.0.0.1 - - [27/May/2023 23:01:15] "[35m[1mPOST /main/login HTTP/1.1[0m" 500 -
[2023-05-27 23:01:45,144] INFO in _internal: 127.0.0.1 - - [27/May/2023 23:01:45] "GET /main/login HTTP/1.1" 200 -
[2023-05-27 23:01:50,285] INFO in _internal: 127.0.0.1 - - [27/May/2023 23:01:50] "GET /main/ HTTP/1.1" 200 -
[2023-05-27 23:01:50,546] INFO in _internal: 127.0.0.1 - - [27/May/2023 23:01:50] "[33mGET /static/css/bootstrap.min.css HTTP/1.1[0m" 404 -
[2023-05-27 23:02:23,745] ERROR in app: Exception on /main/login [POST]
Traceback (most recent call last):
  File "D:\CODES\flask_security\venv\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CODES\flask_security\venv\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CODES\flask_security\venv\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CODES\flask_security\venv\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CODES\flask_security\venv\Lib\site-packages\flask_limiter\extension.py", line 1191, in __inner
    R, flask.current_app.ensure_sync(cast(Callable[P, R], obj))(*a, **k)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CODES\flask_security\app\routes.py", line 160, in login
    user = User.query.filter_by(email=form.email.data).first()
                                      ^^^^^^^^^^
AttributeError: 'LoginForm' object has no attribute 'email'
[2023-05-27 23:02:23,747] INFO in _internal: 127.0.0.1 - - [27/May/2023 23:02:23] "[35m[1mPOST /main/login HTTP/1.1[0m" 500 -
[2023-05-27 23:03:30,675] INFO in _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[2023-05-27 23:03:30,676] INFO in _internal: [33mPress CTRL+C to quit[0m
[2023-05-27 23:03:33,204] INFO in _internal: 127.0.0.1 - - [27/May/2023 23:03:33] "GET /main/login HTTP/1.1" 200 -
[2023-05-27 23:03:37,344] INFO in _internal: 127.0.0.1 - - [27/May/2023 23:03:37] "POST /main/login HTTP/1.1" 200 -
[2023-05-27 23:03:55,061] INFO in _internal: 127.0.0.1 - - [27/May/2023 23:03:55] "POST /main/login HTTP/1.1" 200 -
[2023-05-27 23:04:05,654] INFO in _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[2023-05-27 23:04:05,654] INFO in _internal: [33mPress CTRL+C to quit[0m
[2023-05-27 23:04:12,047] INFO in _internal: 127.0.0.1 - - [27/May/2023 23:04:12] "POST /main/login HTTP/1.1" 200 -
[2023-05-27 23:04:56,781] INFO in _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[2023-05-27 23:04:56,781] INFO in _internal: [33mPress CTRL+C to quit[0m
[2023-05-27 23:05:00,507] INFO in _internal: 127.0.0.1 - - [27/May/2023 23:05:00] "POST /main/login HTTP/1.1" 200 -
[2023-05-27 23:05:20,588] INFO in _internal: 127.0.0.1 - - [27/May/2023 23:05:20] "GET /main/register HTTP/1.1" 200 -
[2023-05-27 23:06:47,303] INFO in _internal: 127.0.0.1 - - [27/May/2023 23:06:47] "GET /main/login HTTP/1.1" 200 -
[2023-05-27 23:08:37,078] INFO in _internal: 127.0.0.1 - - [27/May/2023 23:08:37] "POST /main/login HTTP/1.1" 200 -
[2023-05-27 23:11:08,790] INFO in _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[2023-05-27 23:11:08,790] INFO in _internal: [33mPress CTRL+C to quit[0m
[2023-05-27 23:11:16,774] INFO in _internal: 127.0.0.1 - - [27/May/2023 23:11:16] "GET /main/login HTTP/1.1" 200 -
[2023-05-27 23:11:22,176] INFO in _internal: 127.0.0.1 - - [27/May/2023 23:11:22] "POST /main/login HTTP/1.1" 200 -
[2023-05-27 23:11:30,497] INFO in _internal: 127.0.0.1 - - [27/May/2023 23:11:30] "GET /main/ HTTP/1.1" 200 -
[2023-05-27 23:11:30,752] INFO in _internal: 127.0.0.1 - - [27/May/2023 23:11:30] "[33mGET /static/css/bootstrap.min.css HTTP/1.1[0m" 404 -
[2023-05-27 23:12:56,065] INFO in _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[2023-05-27 23:12:56,065] INFO in _internal: [33mPress CTRL+C to quit[0m
[2023-05-27 23:12:59,149] INFO in _internal: 127.0.0.1 - - [27/May/2023 23:12:59] "GET /main/ HTTP/1.1" 200 -
[2023-05-27 23:13:25,788] INFO in _internal: 127.0.0.1 - - [27/May/2023 23:13:25] "GET /main/login HTTP/1.1" 200 -
[2023-05-27 23:13:27,477] INFO in _internal: 127.0.0.1 - - [27/May/2023 23:13:27] "GET /main/ HTTP/1.1" 200 -
[2023-05-27 23:13:29,225] INFO in _internal: 127.0.0.1 - - [27/May/2023 23:13:29] "GET /main/register HTTP/1.1" 200 -
[2023-05-27 23:13:31,998] INFO in _internal: 127.0.0.1 - - [27/May/2023 23:13:31] "GET /main/login HTTP/1.1" 200 -
[2023-05-27 23:13:35,574] INFO in _internal: 127.0.0.1 - - [27/May/2023 23:13:35] "GET /main/register HTTP/1.1" 200 -
[2023-05-27 23:13:51,539] INFO in _internal: 127.0.0.1 - - [27/May/2023 23:13:51] "POST /main/register HTTP/1.1" 200 -
